/// Categorias sugeridas para cadastro inicial de materiais por condomínio.
const defaultMaterialCategorySeeds = <({String name, String description})>[
  (name: 'Elétrica', description: 'Materiais elétricos gerais'),
  (name: 'Iluminação', description: 'Lâmpadas, luminárias, reatores e sensores'),
  (name: 'Quadros e disjuntores', description: 'DR, DPS, barramentos e disjuntores'),
  (name: 'Cabos e conectores', description: 'Cabos, terminais e eletrodutos'),
  (name: 'Hidráulica', description: 'Registros, conexões, sifões e torneiras'),
  (name: 'Tubos e conexões', description: 'PVC, cobre, roscáveis, colas e soldas'),
  (name: 'Bombas e pressurização', description: 'Bombas, pressostatos e válvulas'),
  (name: 'Caixas d\'água', description: 'Boias, tampas, limpeza e acessórios'),
  (name: 'Portões e motores', description: 'Motores, cremalheiras, fotocélulas e controles'),
  (name: 'Controle de acesso', description: 'Tags, leitores e fechaduras eletrônicas'),
  (name: 'Ferragens e fechaduras', description: 'Maçanetas, dobradiças e cilindros'),
  (name: 'CFTV', description: 'Câmeras, DVR/NVR, fontes e cabos'),
  (name: 'Interfonia', description: 'Interfones, centrais, ramais e acessórios'),
  (name: 'Alarmes e sensores', description: 'Sensores, sirenes e centrais'),
  (name: 'Alvenaria', description: 'Cimento, argamassa, tijolos e vergalhões'),
  (name: 'Pintura', description: 'Tintas, massas, rolos, lixas e seladores'),
  (name: 'Impermeabilização', description: 'Mantas, selantes e impermeabilizantes'),
  (name: 'Telhado e calhas', description: 'Telhas, rufo, calhas e parafusos'),
  (name: 'Elevadores', description: 'Peças, cabos, botoeiras e sensores'),
  (name: 'Equipamentos gerais', description: 'Ferramentas de uso e consumíveis leves'),
  (name: 'Piscina', description: 'Cloro, filtros, bombas e acessórios'),
  (name: 'Limpeza e higiene', description: 'Produtos de limpeza, panos e desinfetantes'),
  (name: 'Paisagismo', description: 'Adubos, mudas, irrigação e substrato'),
  (name: 'Mobiliário urbano', description: 'Bancos, lixeiras e placas de sinalização'),
  (name: 'Fixação e ferragens', description: 'Parafusos, buchas, arruelas e rebites'),
  (name: 'Adesivos e vedantes', description: 'Silicone, fita veda-rosca e colas'),
  (name: 'Descartáveis e consumíveis', description: 'Luvas, fitas, abrasivos e EPIs leves'),
  (name: 'Outros', description: 'Itens que não se encaixam nas demais categorias'),
];
